# Generated by Django 5.0.4 on 2024-06-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="disasterName",
            field=models.CharField(default="", max_length=100),
        ),
    ]
